/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telasprincipais;

import alasdospacientes.ambulatorio;
import alasdospacientes.maternidade;
import alasdospacientes.oncologia;
import alasdospacientes.pediatria;
import alasdospacientes.traumatologia;

/**
 *
 * @author bruna
 */
public class recepcionista extends javax.swing.JFrame {

    /**
     * Creates new form recepcionista
     */
    public recepcionista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        traumatorlogia = new javax.swing.JButton();
        pediatria = new javax.swing.JButton();
        oncologia = new javax.swing.JButton();
        maternidade = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ambulatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        traumatorlogia.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        traumatorlogia.setForeground(java.awt.Color.blue);
        traumatorlogia.setText("Traumatologia");
        traumatorlogia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traumatorlogiaActionPerformed(evt);
            }
        });

        pediatria.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        pediatria.setForeground(java.awt.Color.blue);
        pediatria.setText("Pediatria");
        pediatria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pediatriaActionPerformed(evt);
            }
        });

        oncologia.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        oncologia.setForeground(java.awt.Color.blue);
        oncologia.setText("Oncologia");
        oncologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oncologiaActionPerformed(evt);
            }
        });

        maternidade.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        maternidade.setForeground(java.awt.Color.blue);
        maternidade.setText("Maternidade");
        maternidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maternidadeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(190, 24, 190));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ala da sua recepção");

        ambulatorio.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        ambulatorio.setForeground(java.awt.Color.blue);
        ambulatorio.setText("Ambulatório");
        ambulatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambulatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(pediatria, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(traumatorlogia, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(maternidade, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(oncologia, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(ambulatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pediatria)
                    .addComponent(traumatorlogia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maternidade)
                    .addComponent(oncologia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ambulatorio)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pediatriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pediatriaActionPerformed
        new loginrecepcionistapediatria().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_pediatriaActionPerformed

    private void traumatorlogiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traumatorlogiaActionPerformed
    new menurecepcionista().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_traumatorlogiaActionPerformed

    private void maternidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maternidadeActionPerformed
   new menurecepcionista().setVisible(true);   
        // TODO add your handling code here:
    }//GEN-LAST:event_maternidadeActionPerformed

    private void oncologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oncologiaActionPerformed
    new menurecepcionista().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_oncologiaActionPerformed

    private void ambulatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambulatorioActionPerformed
     new menurecepcionista().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_ambulatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ambulatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton maternidade;
    private javax.swing.JButton oncologia;
    private javax.swing.JButton pediatria;
    private javax.swing.JButton traumatorlogia;
    // End of variables declaration//GEN-END:variables
}
