
import javax.swing.JOptionPane;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Turma 2017
 */
public class NovoJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NovoJFrame
     */
    
    double num1, num2,resultado;
    char operaçao;
    int igual=0,virgula=0;
    
    
    
    public NovoJFrame() {
        initComponents();
        
    painel.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jProgressBar1 = new javax.swing.JProgressBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jCheckBox1 = new javax.swing.JCheckBox();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        painel = new javax.swing.JPanel();
        btQuatro = new javax.swing.JButton();
        btUm = new javax.swing.JButton();
        btVirgula = new javax.swing.JButton();
        btApagarUmNumero = new javax.swing.JButton();
        btNove = new javax.swing.JButton();
        btSeis = new javax.swing.JButton();
        btVezes = new javax.swing.JButton();
        btAdiçao = new javax.swing.JButton();
        btZero = new javax.swing.JButton();
        BtIgual = new javax.swing.JButton();
        btSete = new javax.swing.JButton();
        btDivisao = new javax.swing.JButton();
        btDois = new javax.swing.JButton();
        BtTres = new javax.swing.JButton();
        BtApagartudo = new javax.swing.JButton();
        btCinco = new javax.swing.JButton();
        btOito = new javax.swing.JButton();
        btMenos = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        Monitor = new javax.swing.JLabel();
        monitor2 = new javax.swing.JLabel();
        btRaiz = new javax.swing.JButton();

        jButton20.setText("jButton20");

        jButton21.setText("jButton21");

        jButton23.setText("jButton23");

        jButton24.setText("jButton24");

        jLabel1.setText("jLabel1");

        jCheckBox1.setText("jCheckBox1");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        painel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                painelKeyPressed(evt);
            }
        });

        btQuatro.setBackground(new java.awt.Color(204, 204, 204));
        btQuatro.setText("4");
        btQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuatroActionPerformed(evt);
            }
        });

        btUm.setBackground(new java.awt.Color(204, 204, 204));
        btUm.setText("1");
        btUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUmActionPerformed(evt);
            }
        });

        btVirgula.setBackground(new java.awt.Color(204, 204, 204));
        btVirgula.setText(".");
        btVirgula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVirgulaActionPerformed(evt);
            }
        });

        btApagarUmNumero.setBackground(new java.awt.Color(204, 204, 204));
        btApagarUmNumero.setText("del");
        btApagarUmNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApagarUmNumeroActionPerformed(evt);
            }
        });

        btNove.setBackground(new java.awt.Color(204, 204, 204));
        btNove.setText("9");
        btNove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNoveActionPerformed(evt);
            }
        });

        btSeis.setBackground(new java.awt.Color(204, 204, 204));
        btSeis.setText("6");
        btSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeisActionPerformed(evt);
            }
        });

        btVezes.setBackground(new java.awt.Color(204, 204, 204));
        btVezes.setText("x");
        btVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVezesActionPerformed(evt);
            }
        });

        btAdiçao.setBackground(new java.awt.Color(204, 204, 204));
        btAdiçao.setText("+");
        btAdiçao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdiçaoActionPerformed(evt);
            }
        });

        btZero.setBackground(new java.awt.Color(204, 204, 204));
        btZero.setText("0");
        btZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btZeroActionPerformed(evt);
            }
        });

        BtIgual.setBackground(new java.awt.Color(204, 204, 204));
        BtIgual.setText("=");
        BtIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIgualActionPerformed(evt);
            }
        });

        btSete.setBackground(new java.awt.Color(204, 204, 204));
        btSete.setText("7");
        btSete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSeteActionPerformed(evt);
            }
        });

        btDivisao.setBackground(new java.awt.Color(204, 204, 204));
        btDivisao.setText("/");
        btDivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDivisaoActionPerformed(evt);
            }
        });

        btDois.setBackground(new java.awt.Color(204, 204, 204));
        btDois.setText("2");
        btDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDoisActionPerformed(evt);
            }
        });

        BtTres.setBackground(new java.awt.Color(204, 204, 204));
        BtTres.setText("3");
        BtTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtTresActionPerformed(evt);
            }
        });

        BtApagartudo.setBackground(new java.awt.Color(204, 204, 204));
        BtApagartudo.setText("Ac");
        BtApagartudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtApagartudoActionPerformed(evt);
            }
        });

        btCinco.setBackground(new java.awt.Color(204, 204, 204));
        btCinco.setText("5");
        btCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCincoActionPerformed(evt);
            }
        });

        btOito.setBackground(new java.awt.Color(204, 204, 204));
        btOito.setText("8");
        btOito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOitoActionPerformed(evt);
            }
        });

        btMenos.setBackground(new java.awt.Color(204, 204, 204));
        btMenos.setText("-");
        btMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenosActionPerformed(evt);
            }
        });

        btAlterar.setText("+-");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        Monitor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        monitor2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btRaiz.setText("√");
        btRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRaizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelLayout = new javax.swing.GroupLayout(painel);
        painel.setLayout(painelLayout);
        painelLayout.setHorizontalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelLayout.createSequentialGroup()
                                .addComponent(BtApagartudo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btRaiz, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btApagarUmNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelLayout.createSequentialGroup()
                                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btSete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btQuatro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btVirgula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(painelLayout.createSequentialGroup()
                                        .addComponent(btZero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btDivisao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelLayout.createSequentialGroup()
                                        .addComponent(btDois)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtTres)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btVezes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelLayout.createSequentialGroup()
                                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btCinco)
                                            .addComponent(btOito))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelLayout.createSequentialGroup()
                                                .addComponent(btNove)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btAdiçao, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(painelLayout.createSequentialGroup()
                                                .addComponent(btSeis)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(painelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Monitor, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(monitor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtIgual, BtTres, btAdiçao, btCinco, btDivisao, btDois, btMenos, btNove, btOito, btQuatro, btSeis, btSete, btUm, btVezes, btVirgula, btZero});

        painelLayout.setVerticalGroup(
            painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(monitor2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Monitor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtApagartudo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btApagarUmNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btRaiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdiçao)
                    .addComponent(btNove)
                    .addComponent(btSete)
                    .addComponent(btOito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btMenos)
                    .addComponent(btSeis)
                    .addComponent(btQuatro)
                    .addComponent(btCinco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btDois, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btVezes)
                        .addComponent(BtTres)
                        .addComponent(btUm)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btDivisao)
                    .addComponent(BtIgual)
                    .addComponent(btZero)
                    .addComponent(btVirgula))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenosActionPerformed
        pegarNum1();
        
        operaçao='-';
        SetarNumwrosNoLabel2();
        igual=0; 
    }//GEN-LAST:event_btMenosActionPerformed

    private void btOitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOitoActionPerformed
        setarNumerosNoLabel('8');
    }//GEN-LAST:event_btOitoActionPerformed

    private void btCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCincoActionPerformed
        setarNumerosNoLabel('5');
    }//GEN-LAST:event_btCincoActionPerformed

    private void BtApagartudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtApagartudoActionPerformed
        ZerarVariaveis();
        igual=0; 
    }//GEN-LAST:event_BtApagartudoActionPerformed

  

    private void BtTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtTresActionPerformed
        setarNumerosNoLabel('3');
    }//GEN-LAST:event_BtTresActionPerformed

    private void btDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDoisActionPerformed
        setarNumerosNoLabel('2');
    }//GEN-LAST:event_btDoisActionPerformed

    private void btDivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDivisaoActionPerformed
      
        pegarNum1();
        operaçao='/';
        SetarNumwrosNoLabel2();
        igual=0; 
    }//GEN-LAST:event_btDivisaoActionPerformed

    private void btSeteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeteActionPerformed
        setarNumerosNoLabel('7');

    }//GEN-LAST:event_btSeteActionPerformed

    private void BtIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIgualActionPerformed
if(igual==0){
        pegarNum2();
        calcular();    
       monitor2.setText(monitor2.getText()+" "+num2);
  igual=1;     
}
    }//GEN-LAST:event_BtIgualActionPerformed

    private void btZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btZeroActionPerformed
        setarNumerosNoLabel('0');
    }//GEN-LAST:event_btZeroActionPerformed

    private void btAdiçaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdiçaoActionPerformed
        pegarNum1();
       
        operaçao='+';
        SetarNumwrosNoLabel2();
        igual=0; 
    }//GEN-LAST:event_btAdiçaoActionPerformed

    private void btVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVezesActionPerformed
     
        pegarNum1();
        operaçao='*';
        SetarNumwrosNoLabel2();
        igual=0; 
    }//GEN-LAST:event_btVezesActionPerformed

    private void btSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSeisActionPerformed
        setarNumerosNoLabel('6');
    }//GEN-LAST:event_btSeisActionPerformed

    private void btNoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNoveActionPerformed
        setarNumerosNoLabel('9');
    }//GEN-LAST:event_btNoveActionPerformed

    private void btApagarUmNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApagarUmNumeroActionPerformed

        apagarDigitos(); 
        igual=0; 
    }//GEN-LAST:event_btApagarUmNumeroActionPerformed

 

    private void btVirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVirgulaActionPerformed
        
        if(virgula==0 ){
        setarNumerosNoLabel('.');
       virgula=1;
       }
       
    }//GEN-LAST:event_btVirgulaActionPerformed

    private void btUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUmActionPerformed
        setarNumerosNoLabel('1');
    }//GEN-LAST:event_btUmActionPerformed

    private void btQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuatroActionPerformed
        setarNumerosNoLabel('4');
    }//GEN-LAST:event_btQuatroActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed

double num= Double.parseDouble(Monitor.getText());
if(num != 0){
num=num* -1;
Monitor.setText(String.valueOf(num));
}
    }//GEN-LAST:event_btAlterarActionPerformed

    private void painelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_painelKeyPressed
      
  if(evt.getKeyChar()=='0' ||
     evt.getKeyChar()=='1' ||
     evt.getKeyChar()=='2' ||
     evt.getKeyChar()=='3' ||
     evt.getKeyChar()=='4' ||
     evt.getKeyChar()=='5' ||
     evt.getKeyChar()=='6' || 
     evt.getKeyChar()=='7' ||
     evt.getKeyChar()=='8' ||
     evt.getKeyChar()=='9'  )
                     
  {
     setarNumerosNoLabel(evt.getKeyChar()); 
  }  
  
  else if(evt.getKeyChar()=='.'){
    if(virgula==0 ){
        setarNumerosNoLabel('.');
       virgula=1;
       }
  }
  else if(evt.getKeyChar()=='+' ||
          evt.getKeyChar()=='-' ||
          evt.getKeyChar()=='*' ||
          evt.getKeyChar()=='/')
          {
  pegarNum1();
  
  operaçao=evt.getKeyChar();
   SetarNumwrosNoLabel2(); 
   igual=0; 
  }        
  else if(evt.getKeyCode()==10)  {
      if(igual==0){
  pegarNum2();
   monitor2.setText(monitor2.getText()+" "+num2);
  calcular();
  igual=1; 
      }
  } 
   else if(evt.getKeyCode()==8)  {
   apagarDigitos();
   igual=0; 
   }
    else if(evt.getKeyCode()==116)  {
   ZerarVariaveis();
   igual=0; 
   } 
    else if(evt.getKeyCode()==17)  {
        double num= Double.parseDouble(Monitor.getText());
  if(num != 0){
num=num* -1;
Monitor.setText(String.valueOf(num));
}
   } 
 //System.out.println(evt.getKeyCode());
    }//GEN-LAST:event_painelKeyPressed

    private void btRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRaizActionPerformed
operaçao='√';
pegarNum1();
calcular();  
    }//GEN-LAST:event_btRaizActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NovoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NovoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtApagartudo;
    private javax.swing.JButton BtIgual;
    private javax.swing.JButton BtTres;
    private javax.swing.JLabel Monitor;
    private javax.swing.JButton btAdiçao;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btApagarUmNumero;
    private javax.swing.JButton btCinco;
    private javax.swing.JButton btDivisao;
    private javax.swing.JButton btDois;
    private javax.swing.JButton btMenos;
    private javax.swing.JButton btNove;
    private javax.swing.JButton btOito;
    private javax.swing.JButton btQuatro;
    private javax.swing.JButton btRaiz;
    private javax.swing.JButton btSeis;
    private javax.swing.JButton btSete;
    private javax.swing.JButton btUm;
    private javax.swing.JButton btVezes;
    private javax.swing.JButton btVirgula;
    private javax.swing.JButton btZero;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JLabel monitor2;
    private javax.swing.JPanel painel;
    // End of variables declaration//GEN-END:variables

public void setarNumerosNoLabel(char numero){
  String texto=Monitor.getText();
if (texto.length()<15){
 if("0".equals(Monitor.getText()) && !".".equals(String.valueOf(numero)))
Monitor.setText("");
texto=texto+numero;
Monitor.setText(texto); 
}  
painel.requestFocus();
}



public void pegarNum1(){

num1=Double.parseDouble(Monitor.getText());
Monitor.setText("0");

 virgula=0;
 painel.requestFocus();
}
public void pegarNum2(){

num2=Double.parseDouble(Monitor.getText());
Monitor.setText("");



}

public void calcular(){
    
    if(num2==0 && (operaçao=='/')){
        JOptionPane.showMessageDialog(null, "Operação invalida!");
        ZerarVariaveis();
    }
    else{
    if(operaçao=='+'){
         virgula=1;
resultado=num1+num2;
}else if(operaçao=='-'){
     virgula=1;
resultado=num1-num2;
}
else if(operaçao=='/'){
     virgula=1;
resultado=num1/num2;
}
else if(operaçao=='*'){
     virgula=1;
resultado=num1*num2;
}
else if(operaçao=='√')  {
virgula=1 ;
resultado=Math.sqrt(num1);

}  
    Monitor.setText(String.valueOf(resultado));
    }
painel.requestFocus();


}

public void SetarNumwrosNoLabel2(){
 monitor2.setText(num1+" "+operaçao);


}
  private void ZerarVariaveis() {
        num1 = 0;
        num2 = 0;
        resultado = 0;
        virgula = 0;
        Monitor.setText("");
        monitor2.setText("");
        painel.requestFocus();
    }
   private void apagarDigitos() {
        String valor_do_Monitor=Monitor.getText();
        if(valor_do_Monitor.length()>2){
            
            if(".".equals(valor_do_Monitor.substring(valor_do_Monitor.length()-2,valor_do_Monitor.length()-1))) {
                valor_do_Monitor= valor_do_Monitor.substring(0, valor_do_Monitor.length()-1);
                Monitor.setText(valor_do_Monitor);
                virgula=0;
            }
            
        }
        if(valor_do_Monitor.length()>1){
            
            if("-".equals(valor_do_Monitor.substring(valor_do_Monitor.length()-2,valor_do_Monitor.length()-1))) {
                valor_do_Monitor= valor_do_Monitor.substring(0, valor_do_Monitor.length()-2);
                Monitor.setText(valor_do_Monitor);
                virgula=0;
            }
            
        }
        
        if(valor_do_Monitor.length()==0){
            Monitor.setText("");
        }
        if(valor_do_Monitor.length()>0){
            
            valor_do_Monitor= valor_do_Monitor.substring(0, valor_do_Monitor.length()-1);
            Monitor.setText(valor_do_Monitor);
        }
        painel.requestFocus();
    }

}
  
  


